CREATE TABLE Dollar (
  id serial,
  name VARCHAR(255) NOT NULL,
  buy DECIMAL(19, 4) NOT NULL,
  sell DECIMAL(19, 4) NOT NULL,
  variation DECIMAL(19, 4) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Euro (
  id serial,
  name VARCHAR(255) NOT NULL,
  buy DECIMAL(19, 4) NOT NULL,
  sell DECIMAL(19, 4) NOT NULL,
  variation DECIMAL(19, 4) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);