CREATE SEQUENCE currency_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE Dollar (
  id BIGINT DEFAULT NEXT VALUE FOR currency_seq PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  buy DECIMAL(19, 4) NOT NULL,
  sell DECIMAL(19, 4) NOT NULL,
  variation DECIMAL(19, 4) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Euro (
  id BIGINT DEFAULT NEXT VALUE FOR currency_seq PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  buy DECIMAL(19, 4) NOT NULL,
  sell DECIMAL(19, 4) NOT NULL,
  variation DECIMAL(19, 4) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);